name = "no-style-please"
license = "MIT"
licenselink = "https://github.com/Masellum/hugo-theme-nostyleplease/blob/main/LICENSE"
description = "a (nearly) no-CSS, fast, minimalist Hugo theme ported from riggraz/no-style-please."
homepage = "https://github.com/Masellum/hugo-theme-nostyleplease"
tags = ["blog", "minimalist"]
features = []
min_version = "0.41.0"

[author]
  name = "Masellum"
  homepage = "Masellum.github.io"

[original]
  name = "riggraz"
  homepage = "https://riggraz.dev/"
  repo = "https://github.com/riggraz/no-style-please"
